#!/bin/bash
   # chkconfig: 2345 95 20
   # description: loadbalancer servo service
   # processname: load-balancer-servo
case "$1" in
  start)
      if ps afx | grep $(</var/run/eucaservo/euca-balancer-servo.pid) | grep -v 'grep'; then
          echo "service already running"
          exit 1
      fi
      export PYTHONPATH=$PYTHONPATH:/root/load-balancer-servo;
      /root/load-balancer-servo/euca-balancer-servo -d;
      ;;
  stop)
      kill -9 $(< /var/run/eucaservo/haproxy.pid)
      kill -9 $(< /var/run/eucaservo/euca-balancer-servo.pid)
      ;;
esac 
