#!/bin/sh
#
# Copyright 2009-2016 Hewlett Packard Enterprise Development Company LP.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
# Please contact Hewlett Packard Enterprise Development Company LP., 6755 Hollister Ave., Goleta
# CA 93117, USA or visit http://www.eucalyptus.com/licenses/ if you need
# additional information or have any questions.

### BEGIN INIT INFO
# Provides:          load-balancer-servo
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Eucalyptus Load Balancer Servo
# Description:       Eucalyptus Load Balancer Servo
### END INIT INFO

. /etc/rc.d/init.d/functions

SERVICE=load-balancer-servo
PROCESS=/usr/bin/load-balancer-servo
PIDFILE=/var/run/load-balancer-servo/servo.pid
BOTO_CONFIG=/etc/load-balancer-servo/boto.cfg
SERVOUSER=servo
LOGLEVEL=debug
BOTO_LOGLEVEL=info

LOCKFILE=/var/lock/subsys/load-balancer-servo
PREP=/usr/libexec/load-balancer-servo/servo-prep
PREP_RESULT=/var/lib/load-balancer-servo/ntp.lock

start() {
    echo -n $"Starting $SERVICE: "
    if [ ! -e $PREP_RESULT ]; then
        $PREP&
    fi
    daemon --user=$SERVOUSER --pidfile=$PIDFILE $PROCESS -d -p $PIDFILE -l $LOGLEVEL -c $BOTO_CONFIG -b $BOTO_LOGLEVEL
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop() {
    echo -n $"Stopping $SERVICE: "
    killproc -p $PIDFILE $PROCESS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    [ -f $PIDFILE ] && rm -f $PIDFILE
}

restart() {
    stop
    start
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p $PIDFILE $PROCESS
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 2
esac
exit $RETVAL

